all: main1 main2 main3 main4

main1: main1.c
	gcc -g -Wall -o main1 main1.c -lpthread -lm

main2: main2.c 
	gcc -g -Wall -o main2 main2.c -lpthread -lm

main3: main3.c
	gcc -g -Wall -o main3 main3.c -lpthread -lm

main4: main4.c 
	gcc -g -Wall -o main4 main4.c -lpthread -lm

client: client.c 
	gcc -g -Wall -o client client.c -lpthread -lm
		
attacker: attacker.c 
	gcc -g -Wall -o attacker attacker.c -lpthread -lm